# Generated by Django 5.0.4 on 2024-07-13 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_product_img_product_product_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='trending',
        ),
    ]
